# Generated by Django 4.2.30 on 2026-09-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='origen',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='perro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
