# Generated by Django 4.2.30 on 2026-09-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_perro_origen_alter_perro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='otros_nombres',
            field=models.CharField(default='', max_length=255),
        ),
    ]
