# Generated by Django 4.2.30 on 2026-09-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_perro_otros_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='perro',
            name='otros_nombres',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
